/*
 * hello.c — Micro-C 6809 hello world for the CoCo cartridge (MAME coco2b)
 *
 * Build and run:
 *   make          build hello.rom
 *   make run      run in MAME coco2b (windowed)
 *   make run-headless   run in MAME without a window (output to terminal)
 *
 * Expected screen output on the CoCo:
 *   Hello from Micro-C 6809!
 *   Count: 1 2 3 4 5
 *
 * Target notes (coco cartridge via coco_test target):
 *
 *   CODE_ORG  = $C003   Code starts here, after the 3-byte autostart preamble
 *   STACK_TOP = $7F00   Top of user RAM (below CoCo BASIC workspace top)
 *   RAM_ORG   = $0600   Globals placed here (above BASIC workspace)
 *   I/O       = CoCo BASIC ROM vectors:
 *                 $A002 CHROUT — output char in A register
 *                 $A000 POLCAT — poll keyboard
 *
 *   Cartridge autostart preamble at $C000-$C002:
 *     $C000 = $55   magic — Extended BASIC looks for this on boot
 *     $C001 = $C0   execution address high byte \
 *     $C002 = $03   execution address low byte   -> JSR $C003 (?begin)
 *
 *   The preamble is patched into the binary by the build script AFTER
 *   objcopy converts the HEX file. The compiler places code starting at
 *   $C003; bytes 0-2 of the raw binary are $FF gap fill that gets replaced.
 *
 *   Startup sequence (generated by mktarget from coco_test.cfg):
 *     ?begin:  LDS  #$7F00    initialise stack
 *              LDX  #$0600    clear BSS ($0600-$0FFD) — CoCo RAM is not
 *              LDD  #0        pre-zeroed; C requires uninit globals = 0
 *     ?clr1:   STD  ,X++
 *              CMPX #$0FFE
 *              BLO  ?clr1
 *              CLR  ?heap     zero heap pointer
 *              JSR  main      call user program
 *     ?exit1:  BRA  ?exit1   spin — cartridge stays alive
 *                            Jumping to BASIC warm start would cause an
 *                            infinite loop: BASIC sees $55 at $C000 and
 *                            immediately re-launches the cartridge.
 *
 * K&R C notes (Micro-C uses K&R, not ANSI):
 *   - Parameter types declared separately, not in the argument list
 *   - All local variable declarations must appear at the TOP of a function,
 *     before any statements
 *   - No // comments
 */

extern putstr(), putchr();

/*
 * itoa_simple — write a decimal integer to the CoCo screen.
 * Recursive; handles non-negative values only.
 */
itoa_simple(n)
    int n;
{
    if (n >= 10)
        itoa_simple(n / 10);
    putchr('0' + n % 10);
}

main()
{
    int i;

    putstr("HELLO FROM MICRO-C 6809!\r");

    putstr("COUNT:");
    i = 1;
    while (i <= 5) {
        putchr(' ');
        itoa_simple(i);
        i = i + 1;
    }
    putstr("\r");
}
