# mc09 environment — generated by make env
# source this file: . ./env.sh
# then optionally set MC09_TARGET=coco before sourcing

MCDIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
export MCDIR

export MCINCLUDE="$MCDIR/include"

_target="${MC09_TARGET:-default}"
case "$_target" in
  coco)   export MCLIBDIR="$MCDIR/targets/coco/lib09" ;;
  usim09) export MCLIBDIR="$MCDIR/targets/usim09/lib09" ;;
  *)      export MCLIBDIR="$MCDIR/lib09" ;;
esac

export PATH="$MCDIR:$PATH"

echo "mc09: MCDIR=$MCDIR  MCLIBDIR=$MCLIBDIR"
